{
  flake.modules.homeManager.dunkshell =
    {
      inputs,
      pkgs,
      ...
    }:
    {
      imports = [
        inputs.dms.homeModules.dank-material-shell
        inputs.dms-plugin-registry.modules.default
        # inputs.dms.homeModules.niri
      ];
      programs.dank-material-shell = {
        enable = true;
        # quickshell.package = pkgs.quickshell;
        # dgop.package = inputs.dgop.packages.${pkgs.system}.default;
        # niri = {
        #   includes = {
        #     enable = true; # Enable config includes hack. Enabled by default.
        #
        #     # override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
        #     originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
        #     filesToInclude = [
        #       # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        #       "alttab" # Please note that niri will throw an error if any of these files are missing.
        #       "binds"
        #       "colors"
        #       "cursor"
        #       "layout"
        #       "outputs"
        #       "windowrules"
        #       "wpblur"
        #     ];
        #   };
        # };

        systemd = {
          enable = true; # Systemd service for auto-start
          restartIfChanged = true; # Auto-restart dms.service when dank-material-shell changes
        };

        enableSystemMonitoring = true;
        # enableDynamicTheming = true;
        #  managePluginSettings = false;
        # plugins = {
        #   # Simply enable plugins by their ID (from the registry)
        #   dankBatteryAlerts.enable = true;
        #   # dockerManager.enable = true;
        #
        #   # Add plugin-specific settings
        #   mediaPlayer.enable = true;
        #
        # };
      };
    };
}
