{
  imports = [
    ./audio.nix
    ./boot.nix
    ./env.nix
    ./kernel.nix
    ./network.nix
    ./nix.nix
    ./timezone.nix
    ./user.nix
    ./touchpad.nix
    ./gc.nix
    ./hyprland.nix
    ./locale.nix
    ./greetd.nix
    ./nh.nix
    ./autoupdate.nix
    ./docker.nix
    ./libvirt.nix
    ./postgres.nix
    ./nix-ld.nix
  ];
}
